### PR TITLE
Format TX Power

### PR DESCRIPTION
**Pull request by askpatrickw**
TX Power was not appearing properly as an INT in Advertisement.

### CODE REVIEW

**Comment by WayneKeenan** [comment]
Please could you double check if `byteorder=sys.byteorder` should be less system dependant and be replaced by `byteorder='little'` ?

**Comment by askpatrickw** [comment]
In thinking about environments where it might be big-endian AND bluetooth capable, I think it is unlikely. But they do have support for [sys.byteorder](https://docs.micropython.org/en/v1.9.3/pyboard/library/sys.html?highlight=sys#sys.byteorder) in MicroPython and that makes me think its _more_ possible than I assume. 

Here's some additional information, let me know what you think. I don't a have a strong opinion either way.

**Current architectures**
"The Intel x86 and AMD64 / x86-64 series of processors use the little-endian format. Other instruction set architectures that follow this convention, allowing only little-endian mode, include Nios II, Andes Technology NDS32, and Qualcomm Hexagon.

Some instruction set architectures allow running software of either endianness on a bi-endian architecture. This includes ARM Aarch64, C-Sky, Power ISA, and RISC-V.

Solely big-endian architectures include the IBM z/Architecture, Freescale ColdFire (which is Motorola 68000 series-based), Atmel AVR32, and OpenRISC. The IBM AIX and Oracle Solaris operating systems on bi-endian Power ISA and SPARC run in big-endian mode; some distributions of Linux on Power have moved to little-endian mode."
source: https://en.wikipedia.org/wiki/Endianness#Current_architectures

**Comment by askpatrickw** [comment]
On second thought, I totally misunderstood your question. You are implying the system is irrelevant to the data coming in over bluetooth. And you're right. [According to this discussion on SO](https://stackoverflow.com/questions/55161408/byte-order-of-multiple-fields-in-one-ble-characteristic), in the Bluetooth Standard bytes are little-endian.

I'll modify the PR.  tx!

**Comment by WayneKeenan** [comment]
Sorry, my fault my question was very vague, I had a few things in mind:

1. The BLE spec say's it's little endian.
2. Do any OS'es perform any 'helpful' recording - I have some niggle in the back of my head...
3. Is there anything in Bleson that tries to be 'helpful' too...  (I was't in position to check)

I'm going with it's just item 1 for now and the fact your PR get something useful out, which is more that it did before.

Thanks for your PR.

**Pull request merged**
